#!/usr/bin/env bash

while [[ -n "$1" ]]; do
  case $1 in
  --project)
    PROJECT_ID="$2"
    shift
    ;;
  *)
    API_KEY_NAME="$1"
    ;;
  esac
  shift
done

[[ -z "$PROJECT_ID" ]] && echo "error: require PROJECT_ID" && exit 1
[[ -z "$API_KEY_NAME" ]] && echo "error: require api key name" && exit 1

SECRET=$(openssl rand -base64 32)

if gcloud secrets --project $PROJECT_ID describe $API_KEY_NAME &>/dev/null; then
  echo "warning: secret already exists, wasn't created ($API_KEY_NAME)" && exit 0
fi

echo -n "$SECRET" | gcloud secrets --project $PROJECT_ID create $API_KEY_NAME \
  --replication-policy="automatic" \
  --data-file=-
